### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Tzy010822** [zouzx/TriplaneGaussian#1]
I think TriplaneGaussian is a wonderful work, when do you plan to release the code? thanks

**Comment by johnren-code** [comment]
looking forward to the released code too!!!

**Comment by zouzx** [comment]
Thank you for your attention. We will release the code soon, perhaps after the paper review. Please stay tuned for updates.

**Comment by zouzx** [comment]
We have released the code and model. Have a try~
- code: https://github.com/VAST-AI-Research/TriplaneGaussian
- model: https://huggingface.co/VAST-AI/TriplaneGaussian
